#AUTO GENERATED BY ADDON

extends CharacterBody3D

const speed = 5.0
const jump_velocity = 4.5
const mouse_sensitivity = 0.003
const zoom_speed = 0.5
const zoom_min = 0.0
const zoom_max = 10.0
const fpp_threshold = 0.5

@onready var spring_arm = $SpringArm3D
@onready var mesh = $MeshInstance3D

var is_right_clicking = false
var is_back_aiming = false
var locked_mouse_pos = Vector2.ZERO
var is_first_person = false

func _ready():
	Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
	get_tree().set_auto_accept_quit(false)

func _notification(what):
	if what == NOTIFICATION_WM_GO_BACK_REQUEST:
		is_back_aiming = !is_back_aiming

		if is_back_aiming:
			locked_mouse_pos = get_viewport().get_mouse_position()
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
		else:
			Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
			get_viewport().warp_mouse(locked_mouse_pos)

		get_viewport().set_input_as_handled()

func set_first_person(enabled: bool):
	if is_first_person == enabled:
		return

	is_first_person = enabled
	mesh.visible = !enabled

	if enabled:
		spring_arm.spring_length = 0.0
		Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
	else:
		spring_arm.spring_length = fpp_threshold + 0.1
		Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)

func _input(event):
	if event is InputEventKey:
		if event.pressed and event.keycode == KEY_ESCAPE:
			if is_first_person:
				Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)

	if event is InputEventMouseButton:
		if event.button_index == MOUSE_BUTTON_LEFT and is_first_person:
			Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)

		if event.button_index == MOUSE_BUTTON_RIGHT and not is_first_person:
			is_right_clicking = event.pressed
			if event.pressed:
				locked_mouse_pos = get_viewport().get_mouse_position()
				Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)
			else:
				Input.set_mouse_mode(Input.MOUSE_MODE_VISIBLE)
				get_viewport().warp_mouse(locked_mouse_pos)

		if event.button_index == MOUSE_BUTTON_WHEEL_UP:
			var new_length = clamp(spring_arm.spring_length - zoom_speed, zoom_min, zoom_max)
			spring_arm.spring_length = new_length
			if new_length <= fpp_threshold:
				set_first_person(true)

		if event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			if is_first_person:
				set_first_person(false)
			else:
				var new_length = clamp(spring_arm.spring_length + zoom_speed, zoom_min, zoom_max)
				spring_arm.spring_length = new_length

	if event is InputEventMouseMotion:
		if is_first_person or is_right_clicking or is_back_aiming:
			rotate_y(-event.relative.x * mouse_sensitivity)
			spring_arm.rotate_x(-event.relative.y * mouse_sensitivity)
			spring_arm.rotation.x = clamp(spring_arm.rotation.x, -1.4, 1.4)

func _physics_process(delta):
	if not is_on_floor():
		velocity += get_gravity() * delta

	if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = jump_velocity

	var input_dir = Input.get_vector("ui_left", "ui_right", "ui_up", "ui_down")
	var direction = (transform.basis * Vector3(input_dir.x, 0, input_dir.y)).normalized()

	if direction:
		velocity.x = direction.x * speed
		velocity.z = direction.z * speed
	else:
		velocity.x = move_toward(velocity.x, 0, speed)
		velocity.z = move_toward(velocity.z, 0, speed)

	move_and_slide()
